services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - backend_container
  
  backend:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - redis
    env_file:
      - .backend_env
    networks:
      - backend_container
      - frontend_container
  frontend:
    build:
      context: ./client/.
      dockerfile: dockerfile
    depends_on:
      - frontend
    ports:
      - 8080:80
    networks:
      - frontend_container

networks:
  backend_container:
     driver: bridge
  frontend_container:
      driver: bridge

    
    
  